### ISSUE TITLE
Errors seen in JOSM plugin integration test (PluginHandlerTestIT)

### ISSUE THREAD

**Issue by don-vip** [maripo/JOSM_easypresets#18]
Hello,
Seen in https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/701/jdk=JDK8/testReport/junit/org.openstreetmap.josm.plugins/PluginHandlerTestIT/testValidityOfAvailablePlugins/

```
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.maripo.josm.movementalert.MovementAlertSettings.load(MovementAlertSettings.java:26)
	at org.maripo.josm.movementalert.MovementAlertPlugin.<init>(MovementAlertPlugin.java:29)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:327)
	at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:786)
	at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:870)
	at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:909)
	at org.openstreetmap.josm.plugins.PluginHandlerTestIT.testValidityOfAvailablePlugins(PluginHandlerTestIT.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.openstreetmap.josm.testutils.JOSMTestRules$TimeoutThread.run(JOSMTestRules.java:503)
java.io.FileNotFoundException: /var/lib/jenkins/jobs/JOSM-Integration/workspace/jdk/JDK8/test/config/unit-josm.home/EasyPresets.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.maripo.josm.easypresets.data.EasyPresets.load(EasyPresets.java:88)
	at org.maripo.josm.easypresets.EasyPresetsPlugin.<init>(EasyPresetsPlugin.java:28)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:327)
	at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:786)
	at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:870)
	at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:909)
	at org.openstreetmap.josm.plugins.PluginHandlerTestIT.testValidityOfAvailablePlugins(PluginHandlerTestIT.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.openstreetmap.josm.testutils.JOSMTestRules$TimeoutThread.run(JOSMTestRules.java:503)
```

**Comment by maripo** [comment]
Thank you for your report. These exceptions occur in try-catch blocks and output stacktraces.
Is it improper to print stacktraces to stdio?
```
			try {
				int v = Integer.parseInt(thresholdStr);
				if (v > 0) {
					threshold = v;
				}
			} catch (NumberFormatException e) {
				e.printStackTrace();
			}
```

**Comment by maripo** [comment]
Thank you for your report. Stack traces above are unnecessary because these exceptions are not caused by errors and handled properly in catch blocks. I'll suppress needless messages.
